### ISSUE TITLE
How to build my own index?

### ISSUE THREAD

**Issue by LMC63** [approach0/pya0#1]
Dear sir, I have checked the example usage and I want to use the search function in my own database. However, I'm confused that I cant find search function in pya0 repo, could you help me locate this function? 
Also, I want to build my own index, which function should I use and where can I find it？
I will be grateful for you reply! @t-k-

**Comment by w32zhong** [comment]
I remember I mentioned to you that there is a Colab containing quite a few examples. Have you checked it out?

For your reference: https://github.com/approach0/search-engine/issues/34

**Comment by LMC63** [comment]
Thanks sir, I will read index part carefully.
