### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by LMC63** [approach0/pya0#2]
Dear sir, I want to install pya0 in new device and I have tried command **pip install pya0** and **conda install pya0** and the following error message showed:

ERROR: Could not find a version that satisfies the requirement pya0 (from versions: none)
ERROR: No matching distribution found for pya0

OS: CentOS 7.9
pip version: 21.2.4

@t-k-

**Comment by w32zhong** [comment]
`from version: none` may suggest that pip could not locate the package, please attach your detailed commands and complete output here.

**Comment by LMC63** [comment]
In windows 10 
command: `pip install pya0`
output:
WARNING: Ignoring invalid distribution -yodbc (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ylint (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ydocstyle (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -upyter-console (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -upyter-client (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -tree (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -tconsole (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -sspec (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -sn1crypto (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rllib3 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rapt (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -pywidgets (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -pyder-kernels (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -penpyxl (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oupsieve (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ortedcontainers (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ope-event (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oml (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -olorama (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -lsxwriter (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -lrd (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -loudpickle (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -lake8 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -json (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -itarray (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -eyring (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ertifi (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -eautifulsoup4 (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -eaborn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -crypt (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -blib (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -azy-object-proxy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ath (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atchdog (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -aramiko (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ackaging (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -abel (c:\programdata\anaconda3\lib\site-packages)
ERROR: Could not find a version that satisfies the requirement pya0 (from versions: none)
ERROR: No matching distribution found for pya0
@t-k-

**Comment by w32zhong** [comment]
Sorry currently pya0 only provides manylinux wheel for Linux. I have not cross-complied the core lib on Windows yet.
