### ISSUE TITLE
Query size limits?

### ISSUE THREAD

**Issue by nohahon** [approach0/pya0#7]
Hi,

upon running the following code in python

`query = [{'str': term, 'type': 'tex'} for term in ['T' for i in range(129)]]
JSON = pya0.search(ix, query, verbose = True, topk= 1)
`
with ix the index created by the test-index script that you provided I get a Segmentation Fault. 129 seems to be the threshold here, as the search terminates correctly when just 128 T's are given in the query.

This behavior seems  to occur irrespective of any resource limits on my shell, as controlled by ulimit.

Thanks for any help!

**Comment by w32zhong** [comment]
Hi @nohahon 

Yes, 128 is the maximum number of terms you can have. The Pya0 package does not do a lot of sanity checks because I mainly use it for research purposes. I am sorry for this inconvenience.

**Comment by nohahon** [comment]
Hi,

 

I see, thank you. We wanted to use the system with entire paragraphs as queries, but we should be fine with automatically selected keywords as well.

**Comment by w32zhong** [comment]
sounds good. I am also trying to address the efficiency issue of searching multiple formulas. Unfortunately, the current search could not.

closing this issue.
