### ISSUE TITLE
Links in the readme file are dead

### ISSUE THREAD

**Issue by nohahon** [approach0/pya0#8]
The links https://github.com/approach0/a0-engine and https://github.com/approach0/a0-crawlers/feeder for creating one's own index don't work and should be updated.

**Comment by w32zhong** [comment]
Sorry, the latter is updated. But the core engine is not open sourced yet. I am planning to open it recently as I am about to graduate, please keep an eye on it.

**Comment by nohahon** [comment]
Ok, cool! Thank you.

**Comment by w32zhong** [comment]
The core engine link is open now. I am closing this.
