### ISSUE TITLE
replace_post_tex: regexp matching not working well with parentheses.

### ISSUE THREAD

**Issue by nohahon** [approach0/pya0#9]
Math-environments enclosed in parentheses are not matched well by replace_inline_tex. What works is the regexp from replace_display_tex, just substituting square brackets by parentheses. I.e. I would propose the substitution:

def replace_inline_tex(s):
    # replace '\\( * \\)'
    regex = re.compile('\\\\\((.+?)\\\\\)', re.DOTALL)
    return re.sub(regex, r"[imath]\1[/imath]", s)

Example text (original):
"In this paper, the authors investigate the double-pole Nahm-type sums \n\\[\n\\mathcal D_{t,s}(w,q) = \\sum_{n_1,\\ldots,n_t\\geq 0} (-w;q)_{n_1} q^{n_s} \\prod_{r=1}^t \\frac{q^{n_rn_{r+1}+n_r}}{(q;q)_{n_r}^2}, \n\\]\nwhere \\(t\\geq 1\\), \\(1\\leq s \\leq t+1\\) and \\(n_{t+1}=0\\). All identities of interest in this paper follow by specialization of \\(w\\). Using the method of quantum dilogarithm, the authors find a representation of \\(\\mathcal D_{t,s}(w,q)\\) in the form of an ordinary Nahm sum (with single poles!) with some extra signs. A theta series type representation for \\(\\mathcal D_{t,s}(w,q)\\) is obtained considering the Bailey pair machinery. Certain Nahm-type sum representations for the (odd modulus) Andrews-Gordon identities, the (even modulus) Andrews-Bressoud identities, and Rogers' false theta functions are proved in this context."
Example text (pipelined through replace_inline_tex):
"In this paper, the authors investigate the double-pole Nahm-type sums \n[imath]\n\\mathcal D_{t,s}(w,q) = \\sum_{n_1,\\ldots,n_t\\geq 0} (-w;q)_{n_1} q^{n_s} \\prod_{r=1}^t \\frac{q^{n_rn_{r+1}+n_r}}{(q;q)_{n_r}^2}, \n[/imath]\nwhere [imath]t\\geq 1\\), \\(1\\leq s \\leq t+1\\) and \\(n_{t+1}=0\\). All identities of interest in this paper follow by specialization of \\(w\\). Using the method of quantum dilogarithm, the authors find a representation of \\(\\mathcal D_{t,s}(w,q)\\) in the form of an ordinary Nahm sum (with single poles!) with some extra signs. A theta series type representation for \\(\\mathcal D_{t,s}(w,q)[/imath] is obtained considering the Bailey pair machinery. Certain Nahm-type sum representations for the (odd modulus) Andrews-Gordon identities, the (even modulus) Andrews-Bressoud identities, and Rogers' false theta functions are proved in this context.", "In this paper, the authors investigate the double-pole Nahm-type sums \n\\[\n\\mathcal D_{t,s}(w,q) = \\sum_{n_1,\\ldots,n_t\\geq 0} (-w;q)_{n_1} q^{n_s} \\prod_{r=1}^t \\frac{q^{n_rn_{r+1}+n_r}}{(q;q)_{n_r}^2}, \n\\]\nwhere \\(t\\geq 1\\), \\(1\\leq s \\leq t+1\\) and \\(n_{t+1}=0\\). All identities of interest in this paper follow by specialization of \\(w\\). Using the method of quantum dilogarithm, the authors find a representation of \\(\\mathcal D_{t,s}(w,q)\\) in the form of an ordinary Nahm sum (with single poles!) with some extra signs. A theta series type representation for \\(\\mathcal D_{t,s}(w,q)\\) is obtained considering the Bailey pair machinery. Certain Nahm-type sum representations for the (odd modulus) Andrews-Gordon identities, the (even modulus) Andrews-Bressoud identities, and Rogers' false theta functions are proved in this context."

**Comment by w32zhong** [comment]
@nohahon Thank you so much for catching this bug.

I patched a non-greedy regex in this commit: https://github.com/approach0/pya0/commit/ab77bdac2df46c7d42be01e2b8538a8f70e80235 

However, I've made the decision to stick to math.stackexchange.com inline math format where it uses double slashes, for example: https://math.stackexchange.com/questions/1886701/justify-a-function-series-is-approximating-another-function

Please modify upstream code accordingly to adapt to your usage. Thanks.
